// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server.Api.Infrastructure;

#nullable disable

namespace Server.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211221210558_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Server.Api.Models.Database.Db_Dummy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("pre_Dummy", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Name 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Name 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Name 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
